### ISSUE TITLE
Uncaught Error: Call to a member function get_items() on bool in [...]

### ISSUE THREAD

**Issue by xgpalex28** [AashikP/item-total-for-wc#1]
Hello,

First of all, thanks for the module. Works as intended.
However, orders can no longer be edited.

Steps to reproduce:

1. Make an order
2. Set the status to Pending (so you can edit the order contents)
3. Try to add a product to the order (or update quantity etc)
4. The frame keeps loading with the spinning icon.

Php throws the error:  Uncaught Error: Call to a member function get_items() on bool in item-total-for-wc.php:45

If you refresh the page, the order is actually edited (product added), but by Ajax is doesn't work anymore.

Thanks!

    wordpress version = 5.8.2
    woocommerce version = 6.0.0
    php version = 7.4.26
    SERVER_SOFTWARE = nginx/1.20.2

**Comment by AashikP** [comment]
Hello @xgpalex28 

Sorry for the delayed response here. I can replicate this behavior on the latest version of WooCommerce + WordPress.

Thank you for reporting this bug. I'll take a look at this soon.

**Comment by AashikP** [comment]
cc @xgpalex28  This is fixed in the latest release https://github.com/AashikP/item-total-for-wc/releases/tag/V1.0.1

There can be a UI improvement on updating/editing existing order in that the item total is aligned to the right on update and stays there until the page is reloaded, but that won't stop/cause any other problems.
